// <auto-generated />
namespace _5204_LearnCodeApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class resourceURL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resourceURL));
        
        string IMigrationMetadata.Id
        {
            get { return "202102150559178_resourceURL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
